server:
  port: 8080

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    url: jdbc:oracle:thin:@localhost:1522/XEPDB1
    username: COLLAGE
    password: Rupa
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
